/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.AnimalController;
import controller.ClienteController;
import java.awt.Color;
import model.Animal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import view.TelaPrincipalForm;


/**
 *
 * @author admin
 */
public class AnimalForm extends javax.swing.JFrame {
    private AnimalController animalController;
    private ClienteController clienteController;
    private int idSelecionado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnimalForm.class.getName());

    /**
     * Creates new form AnimalForm
     */
    public AnimalForm() {
        this.animalController = new AnimalController();
        this.clienteController = new ClienteController();
        this.idSelecionado = idSelecionado;
        
        initComponents();
        getContentPane().setBackground(new Color(245, 247, 250));

        carregaAnimais();
    
        tabelaAnimais.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaAnimais.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaAnimais.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeLabel = new javax.swing.JLabel();
        SexoLabel = new javax.swing.JLabel();
        IdadeLabel = new javax.swing.JLabel();
        ClienteIDLabel = new javax.swing.JLabel();
        EspecieLabel = new javax.swing.JLabel();
        NomeInput = new javax.swing.JTextField();
        SexoInput = new javax.swing.JTextField();
        IdadeInput = new javax.swing.JTextField();
        ClienteIDInput = new javax.swing.JTextField();
        EspecieInput = new javax.swing.JTextField();
        CadastrarButton = new javax.swing.JButton();
        AtualizarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAnimais = new javax.swing.JTable();
        VoltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeLabel.setText("Nome :");

        SexoLabel.setText("Sexo :");

        IdadeLabel.setText("Idade :");

        ClienteIDLabel.setText("Cliente ID :");

        EspecieLabel.setText("Especie : ");

        NomeInput.addActionListener(this::NomeInputActionPerformed);

        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(this::CadastrarButtonActionPerformed);

        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(this::AtualizarButtonActionPerformed);

        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(this::ExcluirButtonActionPerformed);

        tabelaAnimais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Sexo", "Idade", "Cliente", "Espécie"
            }
        ));
        tabelaAnimais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAnimaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAnimais);

        VoltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/left-arrow.png"))); // NOI18N
        VoltarButton.addActionListener(this::VoltarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(CadastrarButton)
                        .addGap(18, 18, 18)
                        .addComponent(AtualizarButton)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(SexoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VoltarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EspecieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ClienteIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(IdadeInput)
                            .addComponent(ClienteIDInput)
                            .addComponent(EspecieInput)
                            .addComponent(SexoInput)
                            .addComponent(NomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(VoltarButton)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(NomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexoLabel)
                    .addComponent(SexoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdadeLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteIDLabel)
                    .addComponent(ClienteIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspecieLabel)
                    .addComponent(EspecieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarButton)
                    .addComponent(AtualizarButton)
                    .addComponent(ExcluirButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeInputActionPerformed

    private void tabelaAnimaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAnimaisMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        int linha = this.tabelaAnimais.getSelectedRow();
        if(linha == -1) return;
        
        this.idSelecionado = Integer.parseInt(this.tabelaAnimais.getValueAt(linha, 0).toString());
        
        NomeInput.setText(this.tabelaAnimais.getValueAt(linha, 1).toString());
        SexoInput.setText(this.tabelaAnimais.getValueAt(linha, 2).toString());
        IdadeInput.setText(this.tabelaAnimais.getValueAt(linha, 3).toString());
        ClienteIDInput.setText(this.tabelaAnimais.getValueAt(linha, 4).toString());
        EspecieInput.setText(this.tabelaAnimais.getValueAt(linha, 5).toString());
    }//GEN-LAST:event_tabelaAnimaisMouseClicked

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        // TODO add your handling code here:
        String nome = NomeInput.getText();
        String sexo = SexoInput.getText();
        int idade = Integer.parseInt(IdadeInput.getText());
        int cliente_id = Integer.parseInt(ClienteIDInput.getText());
        String especie = EspecieInput.getText();
        
        Animal animal = new Animal(nome, sexo, idade, cliente_id, especie);
        boolean result = animalController.cadastraAnimal(animal);
        
        carregaAnimais();
        JOptionPane.showMessageDialog(this, "Animal Cadastrado!");
        limparCampos();        
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        
        String nome = NomeInput.getText();
        String sexo = SexoInput.getText();
        int idade = Integer.parseInt(IdadeInput.getText());
        int cliente_id = Integer.parseInt(ClienteIDInput.getText());
        String especie = EspecieInput.getText();
                
        Animal animal = new Animal(this.idSelecionado, nome, sexo, idade, cliente_id, especie);
        boolean result = animalController.atualizaAnimal(animal);
        
        carregaAnimais();
        JOptionPane.showMessageDialog(this, "Animal Atualizado!");
        limparCampos();
    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        // TODO add your handling code here:
        int id = this.idSelecionado;
        String nome = NomeInput.getText();
        String sexo = SexoInput.getText();
        int idade = Integer.parseInt(IdadeInput.getText());
        int cliente_id = Integer.parseInt(ClienteIDInput.getText());
        String especie = EspecieInput.getText();
        
        Animal animal = new Animal(id, nome, sexo, idade, cliente_id, especie);
        boolean result = this.animalController.apagaAnimal(animal);
        
        if(result) {
            JOptionPane.showMessageDialog(this, "Animal Excluido!");
            carregaAnimais();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o animal!");
        }
        
        limparCampos();
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        // TODO add your handling code here:
        new TelaPrincipalForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarButtonActionPerformed

    private void limparCampos() {
        NomeInput.setText("");
        SexoInput.setText("");
        IdadeInput.setText("");
        ClienteIDInput.setText("");
        EspecieInput.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnimalForm().setVisible(true));
    }
    
    public void carregaAnimais() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaAnimais.getModel();
        
        modelo.setRowCount(0);
        List<Animal> animais = this.animalController.listaAnimais();
        
        for(Animal a: animais) {
            modelo.addRow(new Object[] {
                a.getId(),
                a.getNome(),
                a.getSexo(),
                a.getIdade(),
                a.getClienteId(),
                a.getEspecie()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JTextField ClienteIDInput;
    private javax.swing.JLabel ClienteIDLabel;
    private javax.swing.JTextField EspecieInput;
    private javax.swing.JLabel EspecieLabel;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JTextField IdadeInput;
    private javax.swing.JLabel IdadeLabel;
    private javax.swing.JTextField NomeInput;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField SexoInput;
    private javax.swing.JLabel SexoLabel;
    private javax.swing.JButton VoltarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAnimais;
    // End of variables declaration//GEN-END:variables
}
