/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import controller.ClienteController;
import java.awt.Color;
import java.util.List;
import model.Cliente;
import javax.swing.JOptionPane;
import view.TelaPrincipalForm;
/**
 *
 * @author admin
 */
public class ClienteForm extends javax.swing.JFrame {
    private ClienteController clienteController;  
    private int idSelecionado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteForm.class.getName());

    /**
     * Creates new form ClienteForm
     */
    public ClienteForm() {
        this.clienteController = new ClienteController();
        this.idSelecionado = idSelecionado;
        initComponents();
        getContentPane().setBackground(new Color(245, 247, 250));
        LabelFormErro.setVisible(false);

        carregaClientes();
        
        tabelaClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeLabel = new javax.swing.JLabel();
        CPFLabel = new javax.swing.JLabel();
        TelefoneLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        NomeInput = new javax.swing.JTextField();
        CPFInput = new javax.swing.JTextField();
        TelefoneInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        CadastrarButton = new javax.swing.JButton();
        AtualizarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        ExcluirButton = new javax.swing.JButton();
        VoltarButton = new javax.swing.JButton();
        LabelFormErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeLabel.setBackground(new java.awt.Color(51, 51, 51));
        NomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        NomeLabel.setText("Nome :");

        CPFLabel.setBackground(new java.awt.Color(51, 51, 51));
        CPFLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CPFLabel.setForeground(new java.awt.Color(51, 51, 51));
        CPFLabel.setText("CPF :");

        TelefoneLabel.setBackground(new java.awt.Color(51, 51, 51));
        TelefoneLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TelefoneLabel.setForeground(new java.awt.Color(51, 51, 51));
        TelefoneLabel.setText("Telefone :");

        EmailLabel.setBackground(new java.awt.Color(51, 51, 51));
        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(51, 51, 51));
        EmailLabel.setText("Email : ");

        NomeInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeInput.addActionListener(this::NomeInputActionPerformed);

        CPFInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TelefoneInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        EmailInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailInput.addActionListener(this::EmailInputActionPerformed);

        CadastrarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CadastrarButton.setForeground(new java.awt.Color(51, 51, 51));
        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(this::CadastrarButtonActionPerformed);

        AtualizarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AtualizarButton.setForeground(new java.awt.Color(51, 51, 51));
        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(this::AtualizarButtonActionPerformed);

        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jScrollPane1ComponentHidden(evt);
            }
        });

        tabelaClientes.setForeground(new java.awt.Color(51, 51, 51));
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone", "Email"
            }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        ExcluirButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExcluirButton.setForeground(new java.awt.Color(51, 51, 51));
        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(this::ExcluirButtonActionPerformed);

        VoltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/left-arrow.png"))); // NOI18N
        VoltarButton.addActionListener(this::VoltarButtonActionPerformed);

        LabelFormErro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelFormErro.setForeground(new java.awt.Color(255, 0, 0));
        LabelFormErro.setText("Preencha todos os campos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(VoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TelefoneLabel)
                                            .addComponent(CPFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EmailLabel)
                                            .addComponent(NomeLabel))
                                        .addGap(26, 26, 26)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NomeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(CPFInput)
                                    .addComponent(TelefoneInput)
                                    .addComponent(EmailInput)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(CadastrarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AtualizarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExcluirButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelFormErro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(VoltarButton)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeLabel)
                            .addComponent(NomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPFLabel)
                            .addComponent(CPFInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefoneLabel)
                            .addComponent(TelefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLabel)
                            .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CadastrarButton)
                            .addComponent(AtualizarButton)
                            .addComponent(ExcluirButton))
                        .addGap(35, 35, 35)
                        .addComponent(LabelFormErro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        // TODO add your handling code here:
        String nome = NomeInput.getText();
        String cpf = CPFInput.getText();
        String telefone = TelefoneInput.getText();
        String email = EmailInput.getText();
        
        if(verificaCampos()) {
            LabelFormErro.setVisible(true);
        } else {
            System.out.println("ok");
            if(!verificaCPF(cpf)) {
                Cliente cliente = new Cliente(nome, cpf, telefone, email);
                boolean result = clienteController.cadastraCliente(cliente);
        
                carregaClientes();
                JOptionPane.showMessageDialog(this, "Cliente Cadastrado!");
                limparCampos();
                LabelFormErro.setVisible(false);            
            } else {
                JOptionPane.showMessageDialog(this, "CPF já cadastrado");
            }   
        }
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private boolean verificaCampos() {
        return(NomeInput.getText().isEmpty() || CPFInput.getText().isEmpty() || TelefoneInput.getText().isEmpty() || EmailInput.getText().isEmpty());
    }
    
    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed
        // TODO add your handling code here:
        
        String nome = NomeInput.getText();
        String cpf = CPFInput.getText();
        String telefone = TelefoneInput.getText();
        String email = EmailInput.getText();
        if(verificaCampos()) {
            LabelFormErro.setVisible(true);
        } else {
            Cliente cliente = new Cliente(this.idSelecionado, nome, cpf, telefone, email);
            boolean result = clienteController.atualizaCliente(cliente);
        
            carregaClientes();
            JOptionPane.showMessageDialog(this, "Cliente Atualizado!");
            limparCampos();  
            LabelFormErro.setVisible(false);
        }
    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        // TODO add your handling code here:
        int linha = this.tabelaClientes.getSelectedRow();
        if(linha == -1) return;
        
        this.idSelecionado = Integer.parseInt(this.tabelaClientes.getValueAt(linha, 0).toString());
        
        NomeInput.setText(this.tabelaClientes.getValueAt(linha, 1).toString());
        CPFInput.setText(this.tabelaClientes.getValueAt(linha, 2).toString());
        TelefoneInput.setText(this.tabelaClientes.getValueAt(linha, 3).toString());
        EmailInput.setText(this.tabelaClientes.getValueAt(linha, 4).toString()); 
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void jScrollPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1ComponentHidden

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        // TODO add your handling code here:
        int id = this.idSelecionado;
        String nome = NomeInput.getText();
        String cpf = CPFInput.getText();
        String telefone = TelefoneInput.getText();
        String email = EmailInput.getText();
        
        Cliente cliente = new Cliente(id, nome, cpf, telefone, email);
        boolean result = this.clienteController.apagaCliente(cliente);
        
        if(result) {
            JOptionPane.showMessageDialog(this, "Cliente Apagado!");
            carregaClientes();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao apagar o cliente!");
        }
        
        limparCampos();
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        // TODO add your handling code here:
        new TelaPrincipalForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarButtonActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void NomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeInputActionPerformed
    
    public boolean verificaCPF(String cpf) {
        for(int i = 0; i < this.tabelaClientes.getRowCount(); i++) {
            String cpfTabela = tabelaClientes.getValueAt(i, 2).toString(); 
            if(cpfTabela.equals(cpf)) {
                return true;
            }
        }
        
        return false;
    }
    
    private void limparCampos() {
        
        NomeInput.setText("");
        CPFInput.setText("");
        TelefoneInput.setText("");
        EmailInput.setText("");
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        
        java.awt.EventQueue.invokeLater(() -> new ClienteForm().setVisible(true));
    }
    
    public void carregaClientes() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        
        modelo.setRowCount(0);
        List<Cliente> clientes = this.clienteController.listaClientes();
        
        for(Cliente c: clientes) {
            modelo.addRow(new Object[] {
                c.getId(),
                c.getNome(),
                c.getCpf(),
                c.getTelefone(),
                c.getEmail()
            });
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JTextField CPFInput;
    private javax.swing.JLabel CPFLabel;
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JLabel LabelFormErro;
    private javax.swing.JTextField NomeInput;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField TelefoneInput;
    private javax.swing.JLabel TelefoneLabel;
    private javax.swing.JButton VoltarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables
}
