/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Consulta;
import controller.ConsultaController;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import view.TelaPrincipalForm;
/**
 *
 * @author admin
 */
public class ConsultaForm extends javax.swing.JFrame {
    private ConsultaController consultaController;
    private int idSelecionado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaForm.class.getName());

    /**
     * Creates new form ConsultaForm
     */
    public ConsultaForm() {
        this.consultaController = new ConsultaController();
        this.idSelecionado = idSelecionado;
        
        initComponents();
        getContentPane().setBackground(new Color(245, 247, 250));

        carregaConsultas();
        
        tabelaConsultas.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaConsultas.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaConsultas.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        tabelaConsultas.getColumnModel().getColumn(4).setPreferredWidth(40);
        tabelaConsultas.getColumnModel().getColumn(5).setPreferredWidth(40);
        tabelaConsultas.getColumnModel().getColumn(6).setPreferredWidth(40);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataConsultaLabel = new javax.swing.JLabel();
        HoraConsultaLabel = new javax.swing.JLabel();
        DescricaoLabel = new javax.swing.JLabel();
        AnimaLIDLabel = new javax.swing.JLabel();
        VeterinarioIDLabel = new javax.swing.JLabel();
        ClienteIDLabel = new javax.swing.JLabel();
        DataConsultaInput = new javax.swing.JTextField();
        HoraConsultaInput = new javax.swing.JTextField();
        DescricaoInput = new javax.swing.JTextField();
        AnimalIDInput = new javax.swing.JTextField();
        VeterinarioIDInput = new javax.swing.JTextField();
        ClienteIDInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultas = new javax.swing.JTable();
        AgendarButton = new javax.swing.JButton();
        AtualizarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        VoltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DataConsultaLabel.setText("Data Consulta : ");

        HoraConsultaLabel.setText("Hora Consulta : ");

        DescricaoLabel.setText("Descrição :   ");

        AnimaLIDLabel.setText("Animal ID : ");

        VeterinarioIDLabel.setText("Veterinario ID : ");

        ClienteIDLabel.setText("Cliente ID : ");

        HoraConsultaInput.addActionListener(this::HoraConsultaInputActionPerformed);

        VeterinarioIDInput.addActionListener(this::VeterinarioIDInputActionPerformed);

        tabelaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Hora", "Descrição", "Animal ID", "Veterinario ID", "Cliente ID"
            }
        ));
        tabelaConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaConsultas);

        AgendarButton.setText("Agendar");
        AgendarButton.addActionListener(this::AgendarButtonActionPerformed);

        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(this::AtualizarButtonActionPerformed);

        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(this::ExcluirButtonActionPerformed);

        VoltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/left-arrow.png"))); // NOI18N
        VoltarButton.addActionListener(this::VoltarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HoraConsultaLabel)
                                .addComponent(DescricaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AnimaLIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VeterinarioIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ClienteIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AgendarButton, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(DataConsultaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AtualizarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(ExcluirButton))
                            .addComponent(DescricaoInput)
                            .addComponent(AnimalIDInput)
                            .addComponent(VeterinarioIDInput)
                            .addComponent(ClienteIDInput)
                            .addComponent(HoraConsultaInput)
                            .addComponent(DataConsultaInput)))
                    .addComponent(VoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(VoltarButton)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataConsultaLabel)
                            .addComponent(DataConsultaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoraConsultaLabel)
                            .addComponent(HoraConsultaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DescricaoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescricaoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnimalIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnimaLIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VeterinarioIDLabel)
                            .addComponent(VeterinarioIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClienteIDLabel)
                            .addComponent(ClienteIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgendarButton)
                            .addComponent(AtualizarButton)
                            .addComponent(ExcluirButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HoraConsultaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraConsultaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraConsultaInputActionPerformed

    private void VeterinarioIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeterinarioIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VeterinarioIDInputActionPerformed

    private void tabelaConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultasMouseClicked
        // TODO add your handling code here:
        int linha = this.tabelaConsultas.getSelectedRow();
        if(linha == -1) return;
        
        this.idSelecionado = Integer.parseInt(this.tabelaConsultas.getValueAt(linha, 0).toString());
        
        DataConsultaInput.setText(this.tabelaConsultas.getValueAt(linha, 1).toString());
        HoraConsultaInput.setText(this.tabelaConsultas.getValueAt(linha, 2).toString());
        DescricaoInput.setText(this.tabelaConsultas.getValueAt(linha, 3).toString());
        AnimalIDInput.setText(this.tabelaConsultas.getValueAt(linha, 4).toString());
        VeterinarioIDInput.setText(this.tabelaConsultas.getValueAt(linha, 5).toString());
        ClienteIDInput.setText(this.tabelaConsultas.getValueAt(linha, 6).toString());
    }//GEN-LAST:event_tabelaConsultasMouseClicked

    private void AgendarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarButtonActionPerformed
        // TODO add your handling code here:
        String data = DataConsultaInput.getText();
        String hora = HoraConsultaInput.getText();
        String descricao = DescricaoInput.getText();
        int animal_id = Integer.parseInt(AnimalIDInput.getText());
        int veterinario_id = Integer.parseInt(VeterinarioIDInput.getText());
        int cliente_id = Integer.parseInt(ClienteIDInput.getText());
        
        Consulta consulta = new Consulta(data, hora, descricao, animal_id, veterinario_id, cliente_id);
        boolean result = consultaController.cadastraConsulta(consulta);
        
        carregaConsultas();
        JOptionPane.showMessageDialog(this, "Consulta Cadastrada!");
        limparCampos();        
    }//GEN-LAST:event_AgendarButtonActionPerformed

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed
        // TODO add your handling code here:
        String data = DataConsultaInput.getText();
        String hora = HoraConsultaInput.getText();
        String descricao = DescricaoInput.getText();
        
        int animal_id = Integer.parseInt(AnimalIDInput.getText());
        int veterinario_id = Integer.parseInt(VeterinarioIDInput.getText());
        int cliente_id = Integer.parseInt(ClienteIDInput.getText());
                
        Consulta consulta = new Consulta(this.idSelecionado, data, hora, descricao, animal_id, veterinario_id, cliente_id);
        boolean result = consultaController.atualizaConsulta(consulta);
        
        carregaConsultas();
        JOptionPane.showMessageDialog(this, "Consulta Atualizada!");
        limparCampos();
    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        // TODO add your handling code here:
        int id = this.idSelecionado;
        String data = DataConsultaInput.getText();
        String hora = HoraConsultaInput.getText();
        String descricao = DescricaoInput.getText();
        int animal_id = Integer.parseInt(AnimalIDInput.getText());
        int veterinario_id = Integer.parseInt(VeterinarioIDInput.getText());
        int cliente_id = Integer.parseInt(ClienteIDInput.getText());
        
        Consulta consulta = new Consulta(id, data, hora, descricao, animal_id, veterinario_id, cliente_id);
        boolean result = this.consultaController.apagaConsulta(consulta);
        
        if(result) {
            JOptionPane.showMessageDialog(this, "Consulta excluida!");
            carregaConsultas();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir consulta!");
        }
        
        limparCampos();
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        // TODO add your handling code here:
        new TelaPrincipalForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarButtonActionPerformed

    private void limparCampos() {
        HoraConsultaInput.setText("");
        DataConsultaInput.setText("");
        DescricaoInput.setText("");
        AnimalIDInput.setText("");
        VeterinarioIDInput.setText("");
        ClienteIDInput.setText("");
    }
    
    public void carregaConsultas() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaConsultas.getModel();
        
        modelo.setRowCount(0);
        List<Consulta> consultas = this.consultaController.listaConsultas();
        
        for(Consulta c: consultas) {
            modelo.addRow(new Object[] {
                c.getId(),
                c.getDataConsulta(),
                c.getHoraConsulta(),
                c.getDescricao(),
                c.getAnimalId(),
                c.getVeterinarioId(),
                c.getClienteId()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarButton;
    private javax.swing.JLabel AnimaLIDLabel;
    private javax.swing.JTextField AnimalIDInput;
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JTextField ClienteIDInput;
    private javax.swing.JLabel ClienteIDLabel;
    private javax.swing.JTextField DataConsultaInput;
    private javax.swing.JLabel DataConsultaLabel;
    private javax.swing.JTextField DescricaoInput;
    private javax.swing.JLabel DescricaoLabel;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JTextField HoraConsultaInput;
    private javax.swing.JLabel HoraConsultaLabel;
    private javax.swing.JTextField VeterinarioIDInput;
    private javax.swing.JLabel VeterinarioIDLabel;
    private javax.swing.JButton VoltarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaConsultas;
    // End of variables declaration//GEN-END:variables
}
