/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.LoginController;
import java.awt.Color;
import view.TelaPrincipalForm;
/**
 *
 * @author admin
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());
    private LoginController loginController;
    private TelaPrincipalForm telaPrincipalForm;
    private String login;
    private String senha;
    
    /**
     * Creates new form LoginForm
     */
    public LoginForm()
    {
        this.loginController = new LoginController();
        this.telaPrincipalForm = new TelaPrincipalForm();
        this.login = login;
        this.senha = senha;
        initComponents();
        
        getContentPane().setBackground(new Color(245, 247, 250));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginTituloLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        LoginInput = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        LabelLoginError = new javax.swing.JLabel();
        SenhaInput = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginTituloLabel.setBackground(new java.awt.Color(46, 94, 170));
        LoginTituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginTituloLabel.setForeground(new java.awt.Color(46, 94, 170));
        LoginTituloLabel.setText("SISTEMA CLÍNICA VETERINÁRIA");

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(51, 51, 51));
        LoginLabel.setText("Login :");

        SenhaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SenhaLabel.setForeground(new java.awt.Color(51, 51, 51));
        SenhaLabel.setText("Senha :");

        LoginInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginInput.setForeground(new java.awt.Color(51, 51, 51));
        LoginInput.addActionListener(this::LoginInputActionPerformed);

        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("Entrar");
        LoginButton.addActionListener(this::LoginButtonActionPerformed);

        LabelLoginError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelLoginError.setForeground(new java.awt.Color(255, 0, 0));

        SenhaInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SenhaInput.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(LoginTituloLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SenhaLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LoginLabel)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LoginInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SenhaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(LoginButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(LabelLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LoginTituloLabel)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginLabel)
                    .addComponent(LoginInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaLabel)
                    .addComponent(SenhaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(LoginButton)
                .addGap(28, 28, 28)
                .addComponent(LabelLoginError)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginInputActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        this.login = LoginInput.getText();
        this.senha = SenhaInput.getText();
           
        if(this.loginController.AutenticaUsuario(this.login, this.senha) != null) {
           this.telaPrincipalForm.setVisible(true);
           dispose();
        } else {
            LabelLoginError.setText("Usuario ou Senha Incorreto!");            
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLoginError;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField LoginInput;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel LoginTituloLabel;
    private javax.swing.JPasswordField SenhaInput;
    private javax.swing.JLabel SenhaLabel;
    // End of variables declaration//GEN-END:variables
}
