/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import services.RelatorioService;
import model.Animal;
import model.Consulta;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.extensions.ExtensionsEnvironment;
import java.io.InputStream;
/**
 *
 * @author admin
 */
public class RelatorioForm extends javax.swing.JFrame {
    private String opcao;
    private RelatorioService relatorioService;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RelatorioForm.class.getName());

    /**
     * Creates new form RelatorioForm
     */
    public RelatorioForm() {
        this.opcao = opcao;
        this.opcao = "Animais Por Cliente";
        this.relatorioService = new RelatorioService();
        
        initComponents();
        RelatorioLabel2.setVisible(false);
        RelatorioInput2.setVisible(false);
        CamposVaziosLabel.setVisible(false);
    }
      
    public void atualizarCampos() {
        this.opcao = RelatorioSelect.getSelectedItem().toString();
        
        if(this.opcao.equals("Animais Por Cliente")) {
            RelatorioLabel1.setText("Cliente:");
            RelatorioLabel2.setVisible(false);
            RelatorioInput2.setVisible(false);

        } else if (this.opcao.equals("Consultas Por Veterinário")) {
            RelatorioLabel1.setText("Veterinário:");
            RelatorioLabel2.setVisible(false);
            RelatorioInput2.setVisible(false);
        } else if (this.opcao.equals("Consultas Por Período")) {
            RelatorioLabel1.setText("Data Inicial:");
            RelatorioLabel2.setText("Data Final:");

            RelatorioLabel2.setVisible(true);
            RelatorioInput2.setVisible(true);
        }

        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitloRelatorio = new javax.swing.JLabel();
        RelatorioSelect = new javax.swing.JComboBox<>();
        RelatorioInput1 = new javax.swing.JTextField();
        RelatorioInput2 = new javax.swing.JTextField();
        GerarRelatorioButton = new javax.swing.JButton();
        RelatorioLabel1 = new javax.swing.JLabel();
        RelatorioLabel2 = new javax.swing.JLabel();
        CamposVaziosLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitloRelatorio.setText("           Tipo de Relatório ");

        RelatorioSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Animais Por Cliente", "Consultas Por Veterinário", "Consultas Por Período" }));
        RelatorioSelect.addActionListener(this::RelatorioSelectActionPerformed);

        RelatorioInput2.addActionListener(this::RelatorioInput2ActionPerformed);

        GerarRelatorioButton.setText("Gerar Relatório");
        GerarRelatorioButton.addActionListener(this::GerarRelatorioButtonActionPerformed);

        RelatorioLabel1.setText("Cliente");

        RelatorioLabel2.setText("Data Final");

        CamposVaziosLabel.setForeground(new java.awt.Color(255, 0, 0));
        CamposVaziosLabel.setText("Campos vazios não permitidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RelatorioLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RelatorioLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RelatorioInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelatorioSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelatorioInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CamposVaziosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(TitloRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(GerarRelatorioButton)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(TitloRelatorio)
                .addGap(36, 36, 36)
                .addComponent(RelatorioSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RelatorioInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelatorioLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RelatorioLabel2)
                    .addComponent(RelatorioInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(GerarRelatorioButton)
                .addGap(35, 35, 35)
                .addComponent(CamposVaziosLabel)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RelatorioInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatorioInput2ActionPerformed

    private void RelatorioSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioSelectActionPerformed
        // TODO add your handling code here:
        atualizarCampos();
    }//GEN-LAST:event_RelatorioSelectActionPerformed

    private void GerarRelatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarRelatorioButtonActionPerformed
        // TODO add your handling code here:
        if(this.opcao.equals("Animais Por Cliente")) {
            String nome = RelatorioInput1.getText();
            
            if(nome.equals("")) {
                CamposVaziosLabel.setVisible(true);
                return;
            }
            
            List<Animal> animais = this.relatorioService.GeraAnimaisPorCliente(nome);
            CamposVaziosLabel.setVisible(false);
            RelatorioInput1.setText("");
            
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(animais);
            Map<String, Object> parametros = new HashMap<>();
            
            InputStream reportStream = getClass().getResourceAsStream("/relatorios/AnimaisPorCliente.jasper");
            
            try {
               JasperReport jasperReport = (JasperReport) JRLoader.loadObject(reportStream);
               JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, dataSource);
               JasperViewer.viewReport(jasperPrint, false);            
            } catch(Exception e) {
               System.out.println(e.getMessage());
            }

        } else if(this.opcao.equals("Consultas Por Veterinário")) {
            String veterinario = RelatorioInput1.getText();
            
            if(veterinario.equals("")) {
                CamposVaziosLabel.setVisible(true);
                return;
            }
            
            List<Consulta> consultas = this.relatorioService.GeraConsultasPorVeterinario(veterinario);
            CamposVaziosLabel.setVisible(false);
            RelatorioInput1.setText("");
            
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(consultas);
            Map<String, Object> parametros = new HashMap<>();
            
            InputStream reportStream = getClass().getResourceAsStream("/relatorios/ConsultasPorVeterinaio.jasper");
            
            try {
               JasperReport jasperReport = (JasperReport) JRLoader.loadObject(reportStream);
               JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, dataSource);
               JasperViewer.viewReport(jasperPrint, false);            
            } catch(Exception e) {
               System.out.println(e.getMessage());
            }
            
        } else if(this.opcao.equals("Consultas Por Período")) {
            String data_inicial = RelatorioInput1.getText();
            String data_final = RelatorioInput2.getText();
            
            if(data_inicial.equals("") || data_final.equals("")) {
                CamposVaziosLabel.setVisible(true);
                return;
            }
            
            this.relatorioService.GeraConsultasPorPeriodo(data_inicial, data_final);
            CamposVaziosLabel.setVisible(false);
            RelatorioInput1.setText("");
            RelatorioInput2.setText("");
        }
    }//GEN-LAST:event_GerarRelatorioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RelatorioForm().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CamposVaziosLabel;
    private javax.swing.JButton GerarRelatorioButton;
    private javax.swing.JTextField RelatorioInput1;
    private javax.swing.JTextField RelatorioInput2;
    private javax.swing.JLabel RelatorioLabel1;
    private javax.swing.JLabel RelatorioLabel2;
    private javax.swing.JComboBox<String> RelatorioSelect;
    private javax.swing.JLabel TitloRelatorio;
    // End of variables declaration//GEN-END:variables
}
