/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author admin
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ArquivoSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CadastrosClientes = new javax.swing.JMenuItem();
        CadastrosAnimais = new javax.swing.JMenuItem();
        CadastrosVeterinarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ConsultasGerenciar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        RelatoriosGerarRelatorios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        ArquivoSair.setText("Sair");
        ArquivoSair.addActionListener(this::ArquivoSairActionPerformed);
        jMenu1.add(ArquivoSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        CadastrosClientes.setText("Clientes");
        CadastrosClientes.addActionListener(this::CadastrosClientesActionPerformed);
        jMenu2.add(CadastrosClientes);

        CadastrosAnimais.setText("Animais");
        jMenu2.add(CadastrosAnimais);

        CadastrosVeterinarios.setText("Veterinários");
        CadastrosVeterinarios.addActionListener(this::CadastrosVeterinariosActionPerformed);
        jMenu2.add(CadastrosVeterinarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        ConsultasGerenciar.setText("Gerenciar");
        jMenu3.add(ConsultasGerenciar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        RelatoriosGerarRelatorios.setText("Gerar Relatório");
        jMenu4.add(RelatoriosGerarRelatorios);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArquivoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ArquivoSairActionPerformed

    private void CadastrosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrosClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrosClientesActionPerformed

    private void CadastrosVeterinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrosVeterinariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrosVeterinariosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ArquivoSair;
    private javax.swing.JMenuItem CadastrosAnimais;
    private javax.swing.JMenuItem CadastrosClientes;
    private javax.swing.JMenuItem CadastrosVeterinarios;
    private javax.swing.JMenuItem ConsultasGerenciar;
    private javax.swing.JMenuItem RelatoriosGerarRelatorios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
