/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Veterinario;
import controller.VeterinarioController;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import view.TelaPrincipalForm;
/**
 *
 * @author admin
 */
public class VeterinarioForm extends javax.swing.JFrame {
    private VeterinarioController veterinarioController;
    private int idSelecionado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VeterinarioForm.class.getName());

    /**
     * Creates new form VeterinarioForm
     */
    public VeterinarioForm() {
        this.veterinarioController = new VeterinarioController();
        this.idSelecionado = idSelecionado;
        initComponents();
        LabelFormError.setVisible(false);
        getContentPane().setBackground(new Color(245, 247, 250));
        carregaVeterinarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeLabel = new javax.swing.JLabel();
        CRMVLabel = new javax.swing.JLabel();
        TelefoneLabel = new javax.swing.JLabel();
        NomeInput = new javax.swing.JTextField();
        CRMVInput = new javax.swing.JTextField();
        TelefoneInput = new javax.swing.JTextField();
        CadastrarButton = new javax.swing.JButton();
        AtualizarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeterinarios = new javax.swing.JTable();
        VoltarButton = new javax.swing.JButton();
        LabelFormError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        NomeLabel.setText("Nome :");

        CRMVLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CRMVLabel.setForeground(new java.awt.Color(51, 51, 51));
        CRMVLabel.setText("CRMV : ");

        TelefoneLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TelefoneLabel.setForeground(new java.awt.Color(51, 51, 51));
        TelefoneLabel.setText("Telefone :");

        NomeInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeInput.addActionListener(this::NomeInputActionPerformed);

        CRMVInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TelefoneInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TelefoneInput.addActionListener(this::TelefoneInputActionPerformed);

        CadastrarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CadastrarButton.setForeground(new java.awt.Color(51, 51, 51));
        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(this::CadastrarButtonActionPerformed);

        AtualizarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AtualizarButton.setForeground(new java.awt.Color(51, 51, 51));
        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(this::AtualizarButtonActionPerformed);

        ExcluirButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExcluirButton.setForeground(new java.awt.Color(51, 51, 51));
        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(this::ExcluirButtonActionPerformed);

        tabelaVeterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CRMV", "Telefone"
            }
        ));
        tabelaVeterinarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeterinariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVeterinarios);

        VoltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/left-arrow.png"))); // NOI18N
        VoltarButton.addActionListener(this::VoltarButtonActionPerformed);

        LabelFormError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelFormError.setForeground(new java.awt.Color(255, 0, 0));
        LabelFormError.setText("Preencha todos os campos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TelefoneLabel)
                                .addGap(5, 5, 5)
                                .addComponent(TelefoneInput))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CRMVLabel)
                                .addGap(16, 16, 16)
                                .addComponent(CRMVInput))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(NomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(VoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(CadastrarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AtualizarButton)
                        .addGap(12, 12, 12)
                        .addComponent(ExcluirButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(LabelFormError)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(VoltarButton)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(NomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CRMVLabel)
                    .addComponent(CRMVInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefoneLabel)
                    .addComponent(TelefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarButton)
                    .addComponent(AtualizarButton)
                    .addComponent(ExcluirButton))
                .addGap(39, 39, 39)
                .addComponent(LabelFormError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeInputActionPerformed

    private void TelefoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneInputActionPerformed

    private void tabelaVeterinariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeterinariosMouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
        int linha = this.tabelaVeterinarios.getSelectedRow();
        if(linha == -1) return;
        
        this.idSelecionado = Integer.parseInt(this.tabelaVeterinarios.getValueAt(linha, 0).toString());
        NomeInput.setText(this.tabelaVeterinarios.getValueAt(linha, 1).toString());
        CRMVInput.setText(this.tabelaVeterinarios.getValueAt(linha, 2).toString());
        TelefoneInput.setText(this.tabelaVeterinarios.getValueAt(linha, 3).toString());
    }//GEN-LAST:event_tabelaVeterinariosMouseClicked

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        // TODO add your handling code here:
        
        if(verificaCampos()) {
            LabelFormError.setVisible(true);
        } else {
            String nome = NomeInput.getText();
            String crmv = CRMVInput.getText();
            String telefone = TelefoneInput.getText();
        
            Veterinario veterinario = new Veterinario(nome, crmv, telefone);
            boolean result = veterinarioController.cadastraVeterinario(veterinario);
        
            if(result) {
                carregaVeterinarios();
                JOptionPane.showMessageDialog(this, "Veterinario Cadastrado!");
                limparCampos(); 
            } else {
               JOptionPane.showMessageDialog(this, "Veterinario já Existe!");
            }
            
            LabelFormError.setVisible(false);

        }
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        if(verificaCampos()) {
            LabelFormError.setVisible(true);
        } else {
            String nome = NomeInput.getText();
            String crmv = CRMVInput.getText();
            String telefone = TelefoneInput.getText();
                
            Veterinario veterinario = new Veterinario(this.idSelecionado, nome, crmv, telefone);
            boolean result = veterinarioController.atualizaVeterinario(veterinario);
        
            carregaVeterinarios();
            JOptionPane.showMessageDialog(this, "Veterinario Atualizado!");
            limparCampos();
            LabelFormError.setVisible(false);
        }
    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        // TODO add your handling code here:
        if(verificaCampos()) {
            LabelFormError.setVisible(true);
        } else {
            int id = this.idSelecionado;
            String nome = NomeInput.getText();
            String crmv = CRMVInput.getText();
            String telefone = TelefoneInput.getText();
        
            Veterinario veterinario = new Veterinario(id, nome, crmv, telefone);
            boolean result = this.veterinarioController.apagaVeterinario(veterinario);
        
            if(result) {
                JOptionPane.showMessageDialog(this, "Veterinario Excluido!");
                carregaVeterinarios();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o Veterinario!");
            }
        
            limparCampos();
            LabelFormError.setVisible(false);
        }
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        // TODO add your handling code here:
        new TelaPrincipalForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarButtonActionPerformed

    private boolean verificaCampos() {
        return(NomeInput.getText().isEmpty() || CRMVInput.getText().isEmpty() || TelefoneInput.getText().isEmpty());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VeterinarioForm().setVisible(true));
    }
    
    public void carregaVeterinarios() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaVeterinarios.getModel();
        
        modelo.setRowCount(0);
        List<Veterinario> veterinarios = this.veterinarioController.listaVeterinarios();
        
        for(Veterinario v: veterinarios) {
            modelo.addRow(new Object[] {
                v.getId(),
                v.getNome(),
                v.getCrmv(),
                v.getTelefone()
            });
        }
    }

    private void limparCampos() {
        NomeInput.setText("");
        CRMVInput.setText("");
        TelefoneInput.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JTextField CRMVInput;
    private javax.swing.JLabel CRMVLabel;
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JLabel LabelFormError;
    private javax.swing.JTextField NomeInput;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField TelefoneInput;
    private javax.swing.JLabel TelefoneLabel;
    private javax.swing.JButton VoltarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVeterinarios;
    // End of variables declaration//GEN-END:variables
}
